### Feature Transformation
- feature scaling
- encoding categorical data

## Encoding categorical data
- two types of data
- 1.Numerical - height, weight, price
- 2. categorical - gender, state, branch

### Two types of categorical data
- Nominal data - ex. state, engineering branch, here state has no camparision , or also branch we cant say this branch is higher than other branch
- ordinal data - ordinal data has order some relation between categories, ex. review good, avg, poor, fisrt class, second class, third class, education - hsc, graduation, post graduation, this is ordering of data

### Two types of technique for categorical data
- Ordinal encoding - ordinal data use on input columns
- One Hot Encoding - Nomial data use on input columns

### Lable encoding-
- same as ordinal encoding
- use on only ouput column(target)

In [1]:
import numpy as np
import pandas as pd

In [2]:
education = ['Hsc','Ug','Ug','Pg','Hsc','Pg','Ug','Pg','Pg','Hsc','Hsc','Ug']
reviw = ['Good','Avg','Good','Poor','Avg','Good','Avg','Poor','Poor','Avg','Good','Poor']
purchase = ['yes','no','yes','no','no','yes','no','yes','yes','no','yes','yes']
df=pd.DataFrame({'Education':education,'review':reviw,'purchase':purchase})

In [3]:
df

Education review purchase
0        Hsc   Good      yes
1         Ug    Avg       no
2         Ug   Good      yes
3         Pg   Poor       no
4        Hsc    Avg       no
5         Pg   Good      yes
6         Ug    Avg       no
7         Pg   Poor      yes
8         Pg   Poor      yes
9        Hsc    Avg       no
10       Hsc   Good      yes
11        Ug   Poor      yes

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [6]:
X_train

Education review
4        Hsc    Avg
6         Ug    Avg
2         Ug   Good
7         Pg   Poor
5         Pg   Good
11        Ug   Poor
0        Hsc   Good
1         Ug    Avg
8         Pg   Poor

In [7]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Hsc','Ug','Pg'],['Poor','Avg','Good']])

In [8]:
X_train = oe.fit_transform(X_train)
X_train

array([[0., 1.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.]])

In [9]:
X_test=oe.transform(X_test)

In [10]:
X_test

array([[2., 0.],
       [0., 1.],
       [0., 2.]])

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
y_train=le.fit_transform(y_train)

In [13]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 1])

In [14]:
y_test = le.transform(y_test)

In [15]:
y_test

array([0, 0, 1])

In [16]:
le.classes_

array(['no', 'yes'], dtype=object)

## One Hot Encoding

### Dummy Variable Trap
- basically when apply one hot endcoding there are create n categories column, so keep only n-1 column because of multicolinearity
- in that column are multicolinearity because sum is 1 so always when you apply one hot encoding remove one column
- remove 1st column
- these are all dummy vaiables 
#### Always remove one column when You applying OneHotEncoding

- choose only frequent category whose come most number of time and other categories you can collectively called other categor7

In [17]:
import pandas as pd

In [18]:
car=pd.read_csv('cleaned_car.csv')

In [19]:
car.head()

Unnamed: 0                    name   company  year   Price  kms_driven  \
0           0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1           1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2           2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3           3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4           4               Ford Figo      Ford  2012  175000       41000   

  fuel_type  
0    Petrol  
1    Diesel  
2    Petrol  
3    Diesel  
4    Diesel

In [20]:
car['company'].value_counts()

Maruti        221
Hyundai       139
Mahindra       97
Tata           65
Honda          60
Toyota         36
Chevrolet      34
Renault        33
Ford           30
Volkswagen     19
Skoda          13
Audi           11
Mini            8
BMW             8
Datsun          7
Mitsubishi      6
Nissan          6
Mercedes        6
Fiat            4
Force           4
Hindustan       3
Jaguar          2
Land            1
Jeep            1
Volvo           1
Name: company, dtype: int64

In [21]:
car['fuel_type'].value_counts()

Petrol    428
Diesel    385
LPG         2
Name: fuel_type, dtype: int64

In [22]:
car.drop(columns='Unnamed: 0',inplace=True)
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [23]:
car = car[~car['company'].isin(['Land','Jeep','Volvo'])].reset_index(drop=True)

## using Pandas oneHotEncoding
- but we not use these for machine learning

In [24]:
pd.get_dummies(car,columns=['fuel_type','company'])   # 3 column for fuel_type and other 26 columns for company categori

name  year   Price  kms_driven  fuel_type_Diesel  \
0       Hyundai Santro Xing  2007   80000       45000                 0   
1       Mahindra Jeep CL550  2006  425000          40                 1   
2         Hyundai Grand i10  2014  325000       28000                 0   
3    Ford EcoSport Titanium  2014  575000       36000                 1   
4                 Ford Figo  2012  175000       41000                 1   
..                      ...   ...     ...         ...               ...   
807      Maruti Suzuki Ritz  2011  270000       50000                 0   
808          Tata Indica V2  2009  110000       30000                 1   
809    Toyota Corolla Altis  2009  300000      132000                 0   
810            Tata Zest XM  2018  260000       27000                 1   
811      Mahindra Quanto C8  2013  390000       40000                 1   

     fuel_type_LPG  fuel_type_Petrol  company_Audi  company_BMW  \
0                0                 1             0            0   
1                0                 0             0            0   
2                0                 1             0            0   
3                0                 0             0            0   
4                0                 0             0            0   
..             ...               ...           ...          ...   
807              0                 1             0            0   
808              0                 0             0            0   
809              0                 1             0            0   
810              0                 0             0            0   
811              0                 0             0            0   

     company_Chevrolet  ...  company_Maruti  company_Mercedes  company_Mini  \
0                    0  ...               0                 0             0   
1                    0  ...               0                 0             0   
2                    0  ...               0                 0             0   
3                    0  ...               0                 0             0   
4                    0  ...               0                 0             0   
..                 ...  ...             ...               ...           ...   
807                  0  ...               1                 0             0   
808                  0  ...               0                 0             0   
809                  0  ...               0                 0             0   
810                  0  ...               0                 0             0   
811                  0  ...               0                 0             0   

     company_Mitsubishi  company_Nissan  company_Renault  company_Skoda  \
0                     0               0                0              0   
1                     0               0                0              0   
2                     0               0                0              0   
3                     0               0                0              0   
4                     0               0                0              0   
..                  ...             ...              ...            ...   
807                   0               0                0              0   
808                   0               0                0              0   
809                   0               0                0              0   
810                   0               0                0              0   
811                   0               0                0              0   

     company_Tata  company_Toyota  company_Volkswagen  
0               0               0                   0  
1               0               0                   0  
2               0               0                   0  
3               0               0                   0  
4               0               0                   0  
..            ...             ...                 ...  
807             0               0                   0  
808             1  

### K-1 OneHotEncoding

In [25]:
# remove one-one column from both cateogiries
pd.get_dummies(car,columns=['fuel_type','company'],drop_first=True)

name  year   Price  kms_driven  fuel_type_LPG  \
0       Hyundai Santro Xing  2007   80000       45000              0   
1       Mahindra Jeep CL550  2006  425000          40              0   
2         Hyundai Grand i10  2014  325000       28000              0   
3    Ford EcoSport Titanium  2014  575000       36000              0   
4                 Ford Figo  2012  175000       41000              0   
..                      ...   ...     ...         ...            ...   
807      Maruti Suzuki Ritz  2011  270000       50000              0   
808          Tata Indica V2  2009  110000       30000              0   
809    Toyota Corolla Altis  2009  300000      132000              0   
810            Tata Zest XM  2018  260000       27000              0   
811      Mahindra Quanto C8  2013  390000       40000              0   

     fuel_type_Petrol  company_BMW  company_Chevrolet  company_Datsun  \
0                   1            0                  0               0   
1                   0            0                  0               0   
2                   1            0                  0               0   
3                   0            0                  0               0   
4                   0            0                  0               0   
..                ...          ...                ...             ...   
807                 1            0                  0               0   
808                 0            0                  0               0   
809                 1            0                  0               0   
810                 0            0                  0               0   
811                 0            0                  0               0   

     company_Fiat  ...  company_Maruti  company_Mercedes  company_Mini  \
0               0  ...               0                 0             0   
1               0  ...               0                 0             0   
2               0  ...               0                 0             0   
3               0  ...               0                 0             0   
4               0  ...               0                 0             0   
..            ...  ...             ...               ...           ...   
807             0  ...               1                 0             0   
808             0  ...               0                 0             0   
809             0  ...               0                 0             0   
810             0  ...               0                 0             0   
811             0  ...               0                 0             0   

     company_Mitsubishi  company_Nissan  company_Renault  company_Skoda  \
0                     0               0                0              0   
1                     0               0                0              0   
2                     0               0                0              0   
3                     0               0                0              0   
4                     0               0                0              0   
..                  ...             ...              ...            ...   
807                   0               0                0              0   
808                   0               0                0              0   
809                   0               0                0              0   
810                   0               0                0              0   
811                   0               0                0              0   

     company_Tata  company_Toyota  company_Volkswagen  
0               0               0                   0  
1               0               0                   0  
2               0               0                   0  
3               0               0                   0  
4               0               0                   0  
..            ...             ...                 ...  
807             0               0                   0  
808             1               0          

## 3. OneHotEncoding Using Sklearn

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X=car.iloc[:,[0,1,2,4,5]]
y=car['Price']

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [29]:
X_train

name   company  year  kms_driven fuel_type
41   Maruti Suzuki Dzire    Maruti  2013       46000    Diesel
202   Mahindra Quanto C8  Mahindra  2013       20000    Diesel
496   Maruti Suzuki Eeco    Maruti  2015       39000    Petrol
796   Hyundai i20 Select   Hyundai  2011       40000    Petrol
602  Maruti Suzuki Swift    Maruti  2010       74000    Diesel
..                   ...       ...   ...         ...       ...
715   Mahindra KUV100 K8  Mahindra  2018        8000    Diesel
767    Ford Endeavor 4x4      Ford  2019        9000    Diesel
72      Skoda Fabia 1.2L     Skoda  2011       38200    Diesel
235          Audi A4 1.8      Audi  2009       47000    Petrol
37    Renault Duster 110   Renault  2012       38000    Diesel

[649 rows x 5 columns]

In [30]:
y_train

41      349999
202     375000
496     278000
796     290000
602     190000
        ...   
715     560000
767    2900000
72      159500
235     699000
37      501000
Name: Price, Length: 649, dtype: int64

In [31]:

from sklearn.preprocessing import OneHotEncoder

In [32]:
ohe = OneHotEncoder(drop='first', sparse=False, dtype=np.int32)  # drop first column

In [33]:
X_train_new=ohe.fit_transform(X_train[['fuel_type','company']])

In [34]:
X_test_new = ohe.transform(X_test[['fuel_type','company']],)

In [35]:
X_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [36]:
import numpy as np
# now horizantaly concat
np.hstack((X_train[['name','year','kms_driven']].values,X_train_new)).shape

(649, 26)

### 4.OneHotEncoding with Top Categories

In [37]:
caunts = car['company'].value_counts() # whe can choose more than 15 cars of company and other put in uncommon group

In [38]:
car['company'].nunique()

22

In [39]:
repl=caunts[caunts<=15].index
repl

Index(['Skoda', 'Audi', 'Mini', 'BMW', 'Datsun', 'Mitsubishi', 'Nissan',
       'Mercedes', 'Fiat', 'Force', 'Hindustan', 'Jaguar'],
      dtype='object')

In [40]:
pd.get_dummies(car['company'].replace(repl,'uncommon')).sample(10)

Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Tata  Toyota  \
86           0     0      0        0         0       0        0     0       1   
742          0     0      0        1         0       0        0     0       0   
188          0     0      0        0         1       0        0     0       0   
673          0     0      0        0         0       1        0     0       0   
451          0     0      0        1         0       0        0     0       0   
369          0     0      0        1         0       0        0     0       0   
629          0     0      0        0         0       1        0     0       0   
621          1     0      0        0         0       0        0     0       0   
187          0     0      0        1         0       0        0     0       0   
458          0     0      0        0         0       0        0     0       1   

     Volkswagen  uncommon  
86            0         0  
742           0         0  
188           0         0  
673           0         0  
451           0         0  
369           0         0  
629           0         0  
621           0         0  
187           0         0  
458           0         0

# Column Transformer

In [41]:
df=pd.concat([df,pd.DataFrame({'age':[34,12,45,np.nan,32,24,np.nan,16,42,37,np.nan,21]})],axis=1)

In [42]:
df=pd.concat([df,pd.DataFrame({'city':['Nsk','dl','klt','dl','nsk','klt','pn','pn','klt','nsk','pn','dl']})],axis=1)

In [43]:
cough = ['mild','strong','mild','strong','mild','strong','mild','mild','strong','strong','mild','strong']
df=pd.concat([df,pd.DataFrame({'cough':cough})],axis=1)

In [44]:
gender = ['male','female','male','female','male','female','male','female','male','female','male','female']
df = pd.concat([df,pd.DataFrame({'gender':gender})],axis=1)

In [45]:
df=df.iloc[:,[0,1,2,3,4,6,5]]
df.head()

Education review purchase   age city  gender   cough
0       Hsc   Good      yes  34.0  Nsk    male    mild
1        Ug    Avg       no  12.0   dl  female  strong
2        Ug   Good      yes  45.0  klt    male    mild
3        Pg   Poor       no   NaN   dl  female  strong
4       Hsc    Avg       no  32.0  nsk    male    mild

In [46]:
df['city'] = df['city'].replace('Nsk','nsk')

In [47]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['purchase','cough']),df['purchase'],test_size=0.2,random_state=4)

In [48]:
X_train

Education review   age city  gender
9        Hsc    Avg  37.0  nsk  female
8         Pg   Poor  42.0  klt    male
2         Ug   Good  45.0  klt    male
11        Ug   Poor  21.0   dl  female
0        Hsc   Good  34.0  nsk    male
1         Ug    Avg  12.0   dl  female
5         Pg   Good  24.0  klt  female
7         Pg   Poor  16.0   pn  female
10       Hsc   Good   NaN   pn    male

In [49]:
y_train

9      no
8     yes
2     yes
11    yes
0     yes
1      no
5     yes
7     yes
10    yes
Name: purchase, dtype: object

In [50]:
df.isnull().sum()

Education    0
review       0
purchase     0
age          3
city         0
gender       0
cough        0
dtype: int64

## Aam Jindagi

In [51]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer

In [52]:
# adding simple imputer to age column for fill
si = SimpleImputer()
X_train_age=si.fit_transform(X_train[['age']])

# also on X_test fevel
X_test_age = si.transform(X_test[['age']])

In [53]:
X_train_age.shape

(9, 1)

In [54]:
# ordinal encoding -- education ,review
oe = OrdinalEncoder(categories=[['Hsc','Ug','Pg'],['Poor','Avg','Good']])

X_train_edu_rev = oe.fit_transform(X_train[['Education','review']])
X_test_edu_rev = oe.transform(X_test[['Education','review']])

In [55]:
X_train_edu_rev

array([[0., 1.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.]])

In [56]:
# OneHotEncoding --> gender,city
ohe = OneHotEncoder(drop='first',sparse=False)
X_train_gen_ci = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gen_ci = ohe.transform(X_test[['gender','city']])

X_train_gen_ci

array([[0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [57]:
X_train_transformed=np.concatenate((X_train_age,X_train_gen_ci,X_train_edu_rev),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_gen_ci,X_test_edu_rev),axis=1)

In [58]:
X_test_transformed

array([[28.875,  0.   ,  0.   ,  0.   ,  0.   ,  2.   ,  0.   ],
       [32.   ,  1.   ,  0.   ,  1.   ,  0.   ,  0.   ,  1.   ],
       [28.875,  1.   ,  0.   ,  0.   ,  1.   ,  1.   ,  1.   ]])

In [59]:
X_train_transformed

array([[37.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  1.   ],
       [42.   ,  1.   ,  1.   ,  0.   ,  0.   ,  2.   ,  0.   ],
       [45.   ,  1.   ,  1.   ,  0.   ,  0.   ,  1.   ,  2.   ],
       [21.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ],
       [34.   ,  1.   ,  0.   ,  1.   ,  0.   ,  0.   ,  2.   ],
       [12.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  1.   ],
       [24.   ,  0.   ,  1.   ,  0.   ,  0.   ,  2.   ,  2.   ],
       [16.   ,  0.   ,  0.   ,  0.   ,  1.   ,  2.   ,  0.   ],
       [28.875,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  2.   ]])

## Mentos Jindagi

In [60]:
from sklearn.compose import ColumnTransformer

In [61]:
cl_tran = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['age']),
    ('tnf2',OrdinalEncoder(categories=[['Hsc','Ug','Pg'],['Poor','Avg','Good']]),['Education','review']),
    ('tnf3',OneHotEncoder(drop='first',sparse=False),['gender','city'])
],remainder='passthrough')

In [62]:
cl_tran.fit_transform(X_train)

array([[37.   ,  0.   ,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ],
       [42.   ,  2.   ,  0.   ,  1.   ,  1.   ,  0.   ,  0.   ],
       [45.   ,  1.   ,  2.   ,  1.   ,  1.   ,  0.   ,  0.   ],
       [21.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [34.   ,  0.   ,  2.   ,  1.   ,  0.   ,  1.   ,  0.   ],
       [12.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [24.   ,  2.   ,  2.   ,  0.   ,  1.   ,  0.   ,  0.   ],
       [16.   ,  2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ],
       [28.875,  0.   ,  2.   ,  1.   ,  0.   ,  0.   ,  1.   ]])

In [63]:
cl_tran.transform(X_test)

array([[28.875,  2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [32.   ,  0.   ,  1.   ,  1.   ,  0.   ,  1.   ,  0.   ],
       [28.875,  1.   ,  1.   ,  1.   ,  0.   ,  0.   ,  1.   ]])

# PipiLines

In [64]:
import seaborn as sns

In [65]:
titanic = sns.load_dataset('titanic')

In [66]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [67]:
titanic.drop(columns=['class','who','adult_male','deck','embark_town','alive','alone'],inplace=True)

In [68]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [69]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.metrics import accuracy_score,precision_score
from sklearn import set_config

In [70]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(titanic.drop(columns=['survived']),titanic['survived'],test_size=0.2,random_state=12)

In [71]:
X_train.head()

pclass     sex   age  sibsp  parch     fare embarked
8         3  female  27.0      0      2  11.1333        S
150       2    male  51.0      0      0  12.5250        S
221       2    male  27.0      0      0  13.0000        S
365       3    male  30.0      0      0   7.2500        S
324       3    male   NaN      8      2  69.5500        S

In [72]:
y_train

8      1
150    0
221    0
365    0
324    0
      ..
241    1
253    0
390    1
667    0
843    0
Name: survived, Length: 712, dtype: int64

In [73]:
titanic.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [74]:
trf1 = ColumnTransformer(transformers=[
    ('age_impute',SimpleImputer(),[2]),
    ('embarked_impute',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [75]:
trf2 = ColumnTransformer(transformers=[
    ('ohe_sex_emabrked',OneHotEncoder(sparse=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [76]:
trf3 = ColumnTransformer(transformers=[
    ('scaling',MinMaxScaler(),slice(0,10))
])

In [77]:
trf4 = SelectKBest(score_func=chi2,k=3)

In [78]:
trf5 = DecisionTreeClassifier(max_depth=34,max_features=0.9,random_state=121)

In [79]:
set_config(display='diagram')

In [80]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [81]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('age_impute', SimpleImputer(),
                                                  [2]),
                                                 ('embarked_impute',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_emabrked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scaling', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=3,
                             score_func=<function chi2 at 0x000001F032103550>)),
                ('trf5',
                 DecisionTreeClassifier(max_depth=34, max_features=0.9,
                                        random_state=121))])

In [82]:
y_pred = pipe.predict(X_test)

In [83]:
accuracy_score(y_test,y_pred)

0.6033519553072626

In [84]:
precision_score(y_test,y_pred)

0.6111111111111112

In [85]:
pipe.named_steps['trf1'].transformers_[1][1].statistics_

array(['S'], dtype=object)

In [86]:
pipe.named_steps['trf2'].transformers_[0][1]

OneHotEncoder(handle_unknown='ignore', sparse=False)

## Cross validation using Pipeline

In [87]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe,X_train,y_train,cv=5,scoring='accuracy').mean()

0.6235398404412489

## GridSearchcv using Pipeline

In [88]:
params = {'trf5__max_depth':[1,2,3,4,5,None]}

In [89]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe,params,cv=5,scoring='accuracy')
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('age_impute',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('embarked_impute',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_emabrked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scaling',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=3,
                                                    score_func=<function chi2 at 0x000001F032103550>)),
                                       ('trf5',
                                        DecisionTreeClassifier(max_depth=34,
                                                               max_features=0.9,
                                                               random_state=121))]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [90]:
grid.best_score_

0.6235398404412489

In [91]:
grid.best_params_

{'trf5__max_depth': 2}

## Exporting the Pipeline

In [92]:
import pickle

pickle.dump(pipe,open('pipe_model.pkl','wb'))

In [93]:
pipe1 = pickle.load(open('pipe_model.pkl','rb'))

In [94]:
input_1 = np.array([2,'female',30,1,0,12,'S'],dtype=object).reshape(1,-1)

In [95]:
pipe1.predict(input_1)

C:\Users\harsh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\harsh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)